name: Create and Upload Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install zip and rsync
        run: sudo apt-get update && sudo apt-get install -y zip rsync

      - name: Prepare Directory
        run: |
          mkdir jkmfs
          rsync -ar ./jkmfs/ jkmfs/ --exclude jkmfs
          rm -rf jkmfs/.gitignore
          rm -rf jkmfs/.git-ftp-ignore
          rm -rf jkmfs/.git-ftp.log
          rm -rf jkmfs/bitbucket-pipelines.yml
          rm -rf jkmfs/Gruntfile.js
          rm -rf jkmfs/package.json
          rm -rf jkmfs/admin/assets/js/inc
          rm -rf jkmfs/admin/assets/js/jkmfs-admin.js
          rm -rf jkmfs/admin/assets/css/jkmfs-admin.css
          rm -rf jkmfs/public/assets/js/inc
          rm -rf jkmfs/public/assets/js/jkmfs-public.js
          rm -rf jkmfs/public/assets/css/jkmfs-public.css

      - name: Create ZIP Archive
        run: |
          zip -r jkmfs-${{ github.ref_name }}.zip jkmfs

      - name: Upload ZIP Archive
        uses: actions/upload-artifact@v3
        with:
          name: jkmfs-${{ github.ref_name }}.zip
          path: jkmfs-${{ github.ref_name }}.zip
